version: '3.9'
services:
  db:
    restart: always
    image: postgres:15-alpine
    container_name: db_app
    command: -p ${DB_PORT}
    expose:
      - ${DB_PORT}
    env_file:
      - .env

  redis:
    restart: always
    image: bitnami/redis:6.0
    container_name: redis_app
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT_NUMBER=${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  app:
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    command: "sh ./docker/app.sh"
    depends_on:
      - db
      - redis


#  celery:
#    build:
#      context: .
#    container_name: celery_app
#    command: ["/fastapi_app/docker/celery.sh, celery"]
#    depends_on:
#      - redis
#
#  flower:
#    build:
#      context: .
#    container_name: celery_app
#    command: [ "/fastapi_app/docker/celery.sh, flower" ]
#    depends_on:
#      - redis
#      - celery

